version: "3.2"
services:

  cert_generator:
    container_name: kube-cert
    build: .
    volumes:
      - ./kubernetes:/kubernetes


  etcd:
    container_name: kube-etcd
    image: quay.io/coreos/etcd:latest
    ports:
      - "2379"
      - "2380"
    networks:
      - kubernetes
    command: ["etcd", "--advertise-client-urls", "http://0.0.0.0:2379","--listen-client-urls", "http://0.0.0.0:2379"]
    deploy:
      restart_policy:
        condition: always

#TODO: Start API server usingservice IP and pod IP blocks (--service-cluster-ip-range, --pod-ip-range)
  api:
    container_name: kube-api
    image: gcr.io/google_containers/hyperkube-amd64:v1.10.2
    ports:
      - "80"
      - "8080"
      - "443"
    networks:
      kubernetes:
        ipv4_address: 172.200.0.10
    command: ["kube-apiserver", "--etcd-servers", "http://kube-etcd:2379"]
    deploy:
      restart_policy:
        condition: always


#TODO:
# 1) Start Kubelet mounting docker socket
# 2) Start controller manager and other services
# 3) Generate and Volume mount the certs - In Progress


networks:
  kubernetes:
    ipam:
      driver: default
      config:
        - subnet: 172.200.0.0/16


volumes:
  db-data:
