version: "3.2"
services:

  etcd:
    image: quay.io/coreos/etcd:latest
    ports:
      - "2379"
      - "2380"
    networks:
      - kubernetes
    command: ["etcd", "--advertise-client-urls", "http://0.0.0.0:2379","--listen-client-urls", "http://0.0.0.0:2379"]
    deploy:
      restart_policy:
        condition: always

  api:
    image: gcr.io/google_containers/hyperkube-amd64:v1.10.2
    ports:
      - "80"
      - "8080"
      - "443"
    networks:
      - kubernetes
    command: ["kube-apiserver", "--etcd-servers", "etcd:2379"]

    deploy:
      restart_policy:
        condition: always

networks:
  kubernetes:

volumes:
  db-data:
